import { useState } from "react";
import { Panel } from "../../components/Panel";
import { SectionHeader } from "../../components/SectionHeader";
import type { UsePublicRecipesReturn } from "../../hooks/usePublicRecipes";
import type { PublicRecipe } from "../../types/domain";
import { PublicRecipeCard } from "./PublicRecipeCard";
import { PublicRecipeDetail } from "./PublicRecipeDetail";
import { RecentlyGeneratedEmptyState } from "./RecentlyGeneratedEmptyState";
import { RecentlyGeneratedErrorState } from "./RecentlyGeneratedErrorState";

interface RecentlyGeneratedScreenProps {
  publicRecipes: UsePublicRecipesReturn;
}

/**
 * "Recently Generated": a public gallery of recipes generated by anyone using the
 * deployed app, fetched from GET /api/public-recipes — never localStorage, since this is
 * shared across users/devices. Opening a card swaps this screen's own local view to
 * `PublicRecipeDetail`; it never touches AppShell's `SectionKey`, `useVibeCheck`, or
 * Gemini in any way.
 */
export function RecentlyGeneratedScreen({ publicRecipes }: RecentlyGeneratedScreenProps) {
  const [openRecipe, setOpenRecipe] = useState<PublicRecipe | null>(null);
  const { status, recipes, errorMessage, refetch } = publicRecipes;

  if (openRecipe) {
    return (
      <Panel className="relative flex flex-col overflow-hidden lg:h-full">
        <div className="min-h-0 flex-1 overflow-y-auto pr-1">
          <PublicRecipeDetail recipe={openRecipe} onBack={() => setOpenRecipe(null)} />
        </div>
      </Panel>
    );
  }

  return (
    <Panel className="relative flex flex-col overflow-hidden lg:h-full">
      <SectionHeader title="Recently Generated" subtitle="A peek at what the community has been cooking up." />

      <div className="mt-4 min-h-0 flex-1 overflow-y-auto pr-1">
        {status === "loading" ? (
          <p className="py-16 text-center text-sm text-ink-muted">Loading recently generated recipes…</p>
        ) : status === "error" ? (
          <RecentlyGeneratedErrorState message={errorMessage ?? "Something went wrong."} onRetry={refetch} />
        ) : recipes.length === 0 ? (
          <RecentlyGeneratedEmptyState />
        ) : (
          <div className="grid grid-cols-1 gap-4 pb-2 sm:grid-cols-2">
            {recipes.map((recipe) => (
              <PublicRecipeCard key={recipe.id} recipe={recipe} onOpen={() => setOpenRecipe(recipe)} />
            ))}
          </div>
        )}
      </div>
    </Panel>
  );
}
